### PR TITLE
reset message_m after verify_measurement_signature.

### LINKED ISSUE #365: Regardless of verify_measurement_signature success or failure, reset message_m is required
The current code does not reset message_m(L212-L213) when verify_measurement_signature fails. The function returns directly without reset message_m.

https://github.com/jyao1/rust-spdm/blob/0b81da71839bada918c0906b43adae81afbe6339/spdmlib/src/requester/get_measurements_req.rs#L210-L240

### PR DESCRIPTION
**Pull request by longlongyang**
fix #365

### CODE REVIEW

File: spdmlib/src/requester/get_measurements_req.rs [hunk 1]
```diff
@@ -83,6 +83,33 @@ impl<'a> RequesterContext<'a> {
         Ok(writer.used())
     }
 
+    pub fn reset_message_m(&mut self, session_id: Option<u32>) {
+        match session_id {
+            Some(session_id) => {
+                let session = if let Some(s) = self.common.get_session_via_id(session_id) {
+                    s
+                } else {
+                    log::error!("can't find session via session id!");
```
Comment (xiaoyuxlu) [inline spdmlib/src/requester/get_measurements_req.rs:92]: The error is ignored, the previous code will return spdm_result_erre!(EFAULT)

Comment (xiaoyuxlu) [reply spdmlib/src/requester/get_measurements_req.rs:92]: Use https://github.com/jyao1/rust-spdm/issues/370 to track error handling.

**Review by xiaoyuxlu — APPROVED** [review]
