### PR TITLE
fix cargo test failure when hashed-transcript-data is disabled

### LINKED ISSUE #550: `cargo test --no-default-features --features "spdmlib/std,spdmlib/spdm-ring"` will fail

### PR DESCRIPTION
**Pull request by longlongyang**
fix #550

### CODE REVIEW

**Comment by longlongyang** [comment]
known issue of this patch:
cargo test --no-default-features --features "spdmlib/std,spdmlib/spdm-ring" -- --test-threads=1 => pass
cargo test --no-default-features --features "spdmlib/std,spdmlib/spdm-ring"                                 => fail

**Comment by jyao1** [comment]
why not change CI script to use " -- --test-threads=1" ?

File: spdmlib/src/responder/measurement_rsp.rs [hunk 1]
```diff
@@ -518,47 +518,6 @@ mod tests_responder {
                 assert_eq!(payload.number_of_measurement, 1);
                 assert_eq!(payload.slot_id, 0);
                 assert_eq!(payload.measurement_record.number_of_blocks, 1);
-                //index in measurement_record should equal to measurement_operation
```
Comment (jyao1) [inline spdmlib/src/responder/measurement_rsp.rs:521]: why remove the check?

File: spdmlib/src/responder/measurement_rsp.rs [hunk 2]
```diff
@@ -655,113 +614,6 @@ mod tests_responder {
                 //and slot_id should be 0.
                 assert_eq!(payload.slot_id, 0);
                 assert_eq!(payload.measurement_record.number_of_blocks, 5);
-
-                for i in 0..5 {
```
Comment (jyao1) [inline spdmlib/src/responder/measurement_rsp.rs:659]: why remove the check?

**Comment by jyao1** [comment]
Multithread-enabling will be tracked by https://github.com/jyao1/rust-spdm/issues/307.

We can remove " -- --test-threads=1" after #307 is fixed.

File: spdmlib/src/responder/measurement_rsp.rs (hunk 1 above)
Comment (longlongyang) [reply spdmlib/src/responder/measurement_rsp.rs:521]: > why remove the check?

Because the record field of SpdmMeasurementRecordStructure is removed in previous commit, it is not available any more.

https://github.com/jyao1/rust-spdm/commit/d9aa6ca58d9506e1f9b817be4a2e51418c91b5e3#diff-0d8e658ce73b71f92ff8085b92cad0c4281cab172f308d0f05e328f934454f6eR963-R966

**Comment by longlongyang** [comment]
> Multithread-enabling will be tracked by #307.
> 
> We can remove " -- --test-threads=1" after #307 is fixed.

Got it. Updated
